// The Wails-transport implementation of $backend (see vite.config.ts's
// alias) — a straight re-export of the generated bindings. Desktop-only;
// backend.http.ts is the same contract for the web build.
export {
  CurrentWorkspace,
  OpenWorkspace,
  SelectWorkspaceFolder,
  GetCollection,
  CreateCollection,
  RenameCollection,
  DeleteCollection,
  SaveRequest,
  DeleteRequest,
  GetEnvironment,
  SaveEnvironment,
  DeleteEnvironment,
  ExecuteRequest,
  GenerateRequestCode,
  GetTheme,
  GetVersion,
  CancelRequest,
  GetSettings,
  SaveSettings,
  GetCachedResponse,
  ClearResponseCache,
  ClearCachedResponse,
  OpenResponseCacheExternally,
  GetResponseCachePath,
  GetResponseCacheDataURI,
  OpenResponseCacheInFileExplorer,
} from '../wailsjs/go/wailsapp/App.js'
