// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest() {
  return window['go']['wailsapp']['App']['CancelRequest']();
}

export function ClearCachedResponse(arg1) {
  return window['go']['wailsapp']['App']['ClearCachedResponse'](arg1);
}

export function ClearResponseCache() {
  return window['go']['wailsapp']['App']['ClearResponseCache']();
}

export function ControlAPIAddr() {
  return window['go']['wailsapp']['App']['ControlAPIAddr']();
}

export function ControlAPIDocs() {
  return window['go']['wailsapp']['App']['ControlAPIDocs']();
}

export function CreateCollection(arg1) {
  return window['go']['wailsapp']['App']['CreateCollection'](arg1);
}

export function CurrentWorkspace() {
  return window['go']['wailsapp']['App']['CurrentWorkspace']();
}

export function DeleteCollection(arg1) {
  return window['go']['wailsapp']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['wailsapp']['App']['DeleteEnvironment'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['wailsapp']['App']['DeleteRequest'](arg1, arg2);
}

export function DispatchUIAction(arg1, arg2) {
  return window['go']['wailsapp']['App']['DispatchUIAction'](arg1, arg2);
}

export function ExecuteRequest(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['ExecuteRequest'](arg1, arg2, arg3);
}

export function GenerateRequestCode(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['GenerateRequestCode'](arg1, arg2, arg3);
}

export function GetCachedResponse(arg1) {
  return window['go']['wailsapp']['App']['GetCachedResponse'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['wailsapp']['App']['GetCollection'](arg1);
}

export function GetEnvironment(arg1) {
  return window['go']['wailsapp']['App']['GetEnvironment'](arg1);
}

export function GetHeaderCatalog() {
  return window['go']['wailsapp']['App']['GetHeaderCatalog']();
}

export function GetResponseCacheDataURI(arg1) {
  return window['go']['wailsapp']['App']['GetResponseCacheDataURI'](arg1);
}

export function GetResponseCachePath(arg1) {
  return window['go']['wailsapp']['App']['GetResponseCachePath'](arg1);
}

export function GetSettings() {
  return window['go']['wailsapp']['App']['GetSettings']();
}

export function GetTheme() {
  return window['go']['wailsapp']['App']['GetTheme']();
}

export function GetVersion() {
  return window['go']['wailsapp']['App']['GetVersion']();
}

export function ListCollections() {
  return window['go']['wailsapp']['App']['ListCollections']();
}

export function ListEnvironments() {
  return window['go']['wailsapp']['App']['ListEnvironments']();
}

export function OpenResponseCacheExternally(arg1) {
  return window['go']['wailsapp']['App']['OpenResponseCacheExternally'](arg1);
}

export function OpenResponseCacheInFileExplorer(arg1) {
  return window['go']['wailsapp']['App']['OpenResponseCacheInFileExplorer'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['wailsapp']['App']['OpenWorkspace'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['wailsapp']['App']['RenameCollection'](arg1, arg2);
}

export function ReportControlAPIDocs(arg1) {
  return window['go']['wailsapp']['App']['ReportControlAPIDocs'](arg1);
}

export function ReportUIState(arg1) {
  return window['go']['wailsapp']['App']['ReportUIState'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['wailsapp']['App']['SaveEnvironment'](arg1);
}

export function SaveRequest(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveRequest'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['wailsapp']['App']['SaveSettings'](arg1);
}

export function SelectFile() {
  return window['go']['wailsapp']['App']['SelectFile']();
}

export function SelectWorkspaceFolder() {
  return window['go']['wailsapp']['App']['SelectWorkspaceFolder']();
}

export function SetControlAPIAddr(arg1) {
  return window['go']['wailsapp']['App']['SetControlAPIAddr'](arg1);
}

export function Settings() {
  return window['go']['wailsapp']['App']['Settings']();
}

export function UIState() {
  return window['go']['wailsapp']['App']['UIState']();
}

export function WorkspaceRoot() {
  return window['go']['wailsapp']['App']['WorkspaceRoot']();
}
