// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {core} from '../models';
import {httpengine} from '../models';
import {headercatalog} from '../models';
import {settings} from '../models';

export function CancelRequest():Promise<void>;

export function ClearCachedResponse(arg1:string):Promise<void>;

export function ClearResponseCache():Promise<void>;

export function ControlAPIAddr():Promise<string>;

export function ControlAPIDocs():Promise<string>;

export function CreateCollection(arg1:string):Promise<domain.Collection>;

export function CurrentWorkspace():Promise<core.WorkspaceInfo>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string):Promise<void>;

export function DispatchUIAction(arg1:string,arg2:Record<string, any>):Promise<void>;

export function ExecuteRequest(arg1:string,arg2:string,arg3:string):Promise<httpengine.Response>;

export function GenerateRequestCode(arg1:domain.Item,arg2:string,arg3:string):Promise<string>;

export function GetCachedResponse(arg1:string):Promise<httpengine.Response>;

export function GetCollection(arg1:string):Promise<domain.Collection>;

export function GetEnvironment(arg1:string):Promise<domain.Environment>;

export function GetHeaderCatalog():Promise<Array<headercatalog.Entry>>;

export function GetResponseCacheDataURI(arg1:string):Promise<string>;

export function GetResponseCachePath(arg1:string):Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetTheme():Promise<Record<string, string>>;

export function GetVersion():Promise<Record<string, string>>;

export function ListCollections():Promise<Array<core.CollectionSummary>>;

export function ListEnvironments():Promise<Array<core.EnvironmentSummary>>;

export function OpenResponseCacheExternally(arg1:string):Promise<void>;

export function OpenResponseCacheInFileExplorer(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<core.WorkspaceInfo>;

export function RenameCollection(arg1:string,arg2:string):Promise<domain.Collection>;

export function ReportControlAPIDocs(arg1:string):Promise<void>;

export function ReportUIState(arg1:string):Promise<void>;

export function SaveEnvironment(arg1:domain.Environment):Promise<domain.Environment>;

export function SaveRequest(arg1:string,arg2:domain.Item):Promise<domain.Item>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function SelectFile():Promise<string>;

export function SelectWorkspaceFolder():Promise<string>;

export function SetControlAPIAddr(arg1:string):Promise<void>;

export function Settings():Promise<settings.Settings>;

export function UIState():Promise<string>;

export function WorkspaceRoot():Promise<string>;
