// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ControlAPIAddr() {
  return window['go']['wailsapp']['App']['ControlAPIAddr']();
}

export function CurrentWorkspace() {
  return window['go']['wailsapp']['App']['CurrentWorkspace']();
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['wailsapp']['App']['DeleteRequest'](arg1, arg2);
}

export function DispatchUIAction(arg1, arg2) {
  return window['go']['wailsapp']['App']['DispatchUIAction'](arg1, arg2);
}

export function ExecuteRequest(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['ExecuteRequest'](arg1, arg2, arg3);
}

export function GetCollection(arg1) {
  return window['go']['wailsapp']['App']['GetCollection'](arg1);
}

export function GetEnvironment(arg1) {
  return window['go']['wailsapp']['App']['GetEnvironment'](arg1);
}

export function GetHeaderCatalog() {
  return window['go']['wailsapp']['App']['GetHeaderCatalog']();
}

export function GetTheme() {
  return window['go']['wailsapp']['App']['GetTheme']();
}

export function ListCollections() {
  return window['go']['wailsapp']['App']['ListCollections']();
}

export function ListEnvironments() {
  return window['go']['wailsapp']['App']['ListEnvironments']();
}

export function OpenWorkspace(arg1) {
  return window['go']['wailsapp']['App']['OpenWorkspace'](arg1);
}

export function ReportUIState(arg1) {
  return window['go']['wailsapp']['App']['ReportUIState'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['wailsapp']['App']['SaveEnvironment'](arg1);
}

export function SaveRequest(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveRequest'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['wailsapp']['App']['SelectFile']();
}

export function SelectWorkspaceFolder() {
  return window['go']['wailsapp']['App']['SelectWorkspaceFolder']();
}

export function SetControlAPIAddr(arg1) {
  return window['go']['wailsapp']['App']['SetControlAPIAddr'](arg1);
}

export function UIState() {
  return window['go']['wailsapp']['App']['UIState']();
}

export function WorkspaceRoot() {
  return window['go']['wailsapp']['App']['WorkspaceRoot']();
}
